services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    # volumes:
    #   - db_data:/var/lib/mysql
    ports:
      - 3307:3306
  web:
    build: .
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    mem_limit: 4g
  nginx:
    image: nginx:latest
    volumes:
      - .:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 3006:80
    depends_on:
      - web
      - db
    mem_limit: 4g
# volumes:
#   db_data: {}