services:
  web:
    build: .
    volumes:
      - .:/var/www/html
  nginx:
    image: nginx:latest
    volumes:
      - .:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 9000:80
      - 80:80
    depends_on:
      - web